window.QUOTIFY_DATA = {
  themes: {
    motivation: { fr: "Motivation", en: "Motivation", color: "#c9842a" },
    sagesse: { fr: "Sagesse", en: "Wisdom", color: "#3d7a6a" },
    succes: { fr: "Travail", en: "Work", color: "#2f6b9a" },
    vie: { fr: "Vie", en: "Life", color: "#6b4f9a" },
    amitie: { fr: "Amitié", en: "Friendship", color: "#b85c38" },
    etudes: { fr: "Études", en: "Study", color: "#3a6ea5" },
    humour: { fr: "Humour", en: "Humor", color: "#7a8b2e" }
  },
  quotes: [
    { id: 1, text: "Ce n'est pas parce que les choses sont difficiles que nous n'osons pas, c'est parce que nous n'osons pas qu'elles sont difficiles.", author: "Sénèque", theme: "motivation", lang: "fr" },
    { id: 2, text: "Le succès, c'est se déplacer d'échec en échec sans perdre son enthousiasme.", author: "Winston Churchill", theme: "motivation", lang: "fr" },
    { id: 3, text: "Il n'y a qu'une façon d'échouer, c'est d'abandonner avant d'avoir réussi.", author: "Georges Clemenceau", theme: "motivation", lang: "fr" },
    { id: 4, text: "Fall seven times, stand up eight.", author: "Japanese proverb", theme: "motivation", lang: "en" },
    { id: 5, text: "La discipline est le pont entre les objectifs et les résultats.", author: "Jim Rohn", theme: "motivation", lang: "fr" },
    { id: 36, text: "Be the change you wish to see in the world.", author: "Mahatma Gandhi", theme: "vie", lang: "en" },
    { id: 37, text: "Si tu veux aller vite, va seul. Si tu veux aller loin, allez ensemble.", author: "Proverbe africain", theme: "amitie", lang: "fr" },
    { id: 38, text: "Un seul brin de paille ne tisse pas un panier.", author: "Proverbe africain", theme: "amitie", lang: "fr" },
    { id: 39, text: "La pluie ne tombe pas sur un seul toit.", author: "Proverbe africain", theme: "sagesse", lang: "fr" },
    { id: 40, text: "Quand les racines sont profondes, il n'y a pas lieu de craindre le vent.", author: "Proverbe africain", theme: "motivation", lang: "fr" },
    { id: 41, text: "L'éducation est l'arme la plus puissante qu'on puisse utiliser pour changer le monde.", author: "Nelson Mandela", theme: "etudes", lang: "fr" },
    { id: 42, text: "Education is the most powerful weapon which you can use to change the world.", author: "Nelson Mandela", theme: "etudes", lang: "en" },
    { id: 43, text: "Apprendre sans réfléchir est vain. Réfléchir sans apprendre est dangereux.", author: "Confucius", theme: "etudes", lang: "fr" },
    { id: 46, text: "Un livre ouvert est un cerveau qui parle.", author: "Proverbe", theme: "etudes", lang: "fr" },
    { id: 51, text: "Celui qui déplace une montagne commence par enlever les petites pierres.", author: "Confucius", theme: "succes", lang: "fr" },
    { id: 52, text: "It always seems impossible until it is done.", author: "Nelson Mandela", theme: "motivation", lang: "en" },
    { id: 53, text: "Cela paraît toujours impossible, jusqu'à ce que ce soit fait.", author: "Nelson Mandela", theme: "motivation", lang: "fr" },
    { id: 57, text: "Le savoir est la seule richesse qu'on ne peut pas voler.", author: "Proverbe", theme: "etudes", lang: "fr" },
    { id: 60, text: "Un voyage de mille lieues commence toujours par un premier pas.", author: "Lao Tseu", theme: "motivation", lang: "fr" },
    { id: 6, text: "N'attends pas d'être heureux pour sourire, souris pour être heureux.", author: "Édouard Pailleron", theme: "motivation", lang: "fr" },
    { id: 7, text: "Le meilleur moyen de prédire l'avenir, c'est de le créer.", author: "Peter Drucker", theme: "motivation", lang: "fr" },
    { id: 8, text: "On ne voit bien qu'avec le cœur. L'essentiel est invisible pour les yeux.", author: "Antoine de Saint-Exupéry", theme: "sagesse", lang: "fr" },
    { id: 9, text: "Connais-toi toi-même.", author: "Socrate", theme: "sagesse", lang: "fr" },
    { id: 10, text: "La vraie sagesse est de connaître l'étendue de son ignorance.", author: "Confucius", theme: "sagesse", lang: "fr" },
    { id: 11, text: "Ce que nous savons est une goutte d'eau, ce que nous ignorons est un océan.", author: "Isaac Newton", theme: "sagesse", lang: "fr" },
    { id: 12, text: "The unexamined life is not worth living.", author: "Socrates", theme: "sagesse", lang: "en" },
    { id: 13, text: "Il n'est pas de vent favorable pour celui qui ne sait où il va.", author: "Sénèque", theme: "sagesse", lang: "fr" },
    { id: 14, text: "L'imagination est plus importante que le savoir.", author: "Albert Einstein", theme: "sagesse", lang: "fr" },
    { id: 15, text: "Everything you can imagine is real.", author: "Pablo Picasso", theme: "sagesse", lang: "en" },
    { id: 16, text: "Le seul endroit où le succès précède le travail, c'est dans le dictionnaire.", author: "Vidal Sassoon", theme: "succes", lang: "fr" },
    { id: 17, text: "Le succès n'est pas final, l'échec n'est pas fatal : c'est le courage de continuer qui compte.", author: "Winston Churchill", theme: "succes", lang: "fr" },
    { id: 18, text: "L'échec est simplement l'occasion de recommencer, avec plus d'intelligence.", author: "Henry Ford", theme: "succes", lang: "fr" },
    { id: 19, text: "Success is not the key to happiness. Happiness is the key to success.", author: "Albert Schweitzer", theme: "succes", lang: "en" },
    { id: 20, text: "Petit à petit, l'oiseau fait son nid.", author: "Proverbe", theme: "succes", lang: "fr" },
    { id: 21, text: "La vie, c'est ce qui se passe pendant que tu fais d'autres projets.", author: "John Lennon", theme: "vie", lang: "fr" },
    { id: 22, text: "La vie est vraiment simple, mais nous insistons pour la compliquer.", author: "Confucius", theme: "vie", lang: "fr" },
    { id: 23, text: "In three words I can sum up everything I've learned about life: it goes on.", author: "Robert Frost", theme: "vie", lang: "en" },
    { id: 24, text: "Ne comptez pas les jours, faites que les jours comptent.", author: "Mère Teresa", theme: "vie", lang: "fr" },
    { id: 25, text: "Vivre est la chose la plus rare au monde. La plupart des gens existent, c'est tout.", author: "Oscar Wilde", theme: "vie", lang: "fr" },
    { id: 26, text: "Un ami, c'est quelqu'un qui te connaît vraiment et qui reste.", author: "Anonyme", theme: "amitie", lang: "fr" },
    { id: 27, text: "L'amitié double les joies et réduit de moitié les peines.", author: "Cicéron", theme: "amitie", lang: "fr" },
    { id: 28, text: "A real friend is one who walks in when the rest of the world walks out.", author: "Walter Winchell", theme: "amitie", lang: "en" },
    { id: 29, text: "On juge un arbre à ses fruits, et un ami à sa constance.", author: "Proverbe", theme: "amitie", lang: "fr" },
    { id: 30, text: "L'argent ne fait pas le bonheur, mais il aide à prendre le bus pour y aller.", author: "Anonyme", theme: "humour", lang: "fr" },
    { id: 31, text: "Le travail, c'est la santé. Rien faire, c'est la conserver.", author: "Henri Salvador", theme: "humour", lang: "fr" },
    { id: 32, text: "I'm not lazy, I'm on energy-saving mode.", author: "Anonymous", theme: "humour", lang: "en" },
    { id: 33, text: "Il vaut mieux rire de ses erreurs que d'en pleurer.", author: "Anonyme", theme: "humour", lang: "fr" },
    { id: 34, text: "Qui trop se presse arrive le premier à se tromper.", author: "Anonyme", theme: "humour", lang: "fr" },
    { id: 35, text: "Commence par faire le nécessaire, puis le possible, et tu atteindras l'impossible.", author: "François d'Assise", theme: "motivation", lang: "fr" }
  ]
};
